root: true
env:
  es2021: true
  node: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
extends:
  - eslint:recommended
  - xo
rules:
  indent:
    - error
    - 4
    -
      SwitchCase: 1
  comma-dangle: [error, never]
  max-len: [error, 150]
  camelcase: off
  curly: off
  capitalized-comments: off
  object-curly-spacing: off
  padding-line-between-statements: off
globals:
  describe: true
  it: true
  beforeEach: true
  afterEach: true
  before: true
  after: true
